MVCUI/Areas/AdminSpecial/Controllers/AuthorController.cs
using Kitap.BLL.RepositoryPattern.ConcreteRepo;
using Kitap.MODEL.Entities;
using MVCUI.AuthenticationClasses;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCUI.Areas.AdminSpecial.Controllers
{
    [AdminAuthentication]
    public class AuthorController : Controller
    {
        AuthorRepository a_repo = new AuthorRepository();
        // GET: AdminSpecial/Author
        public ActionResult AuthorList()
        {
            return View(a_repo.SelectActives());
        }

        public ActionResult AddAuthor()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddBook(Author item)
        {
            
            a_repo.Add(item);

            return RedirectToAction("AuthorList");
        }

        public ActionResult UpdateAuthor(int id)
        {
            return View(a_repo.GetByID(id));
        }

        [HttpPost]
        public ActionResult UpdateAuthor(Author item)
        {
            
            a_repo.Update(item);

            return RedirectToAction("AuthorList");
        }

        public ActionResult DeleteAuthor(int id)
        {
            a_repo.SpecialDelete(id);
            return RedirectToAction("AuthorList");
        }
    }
}

MVCUI/Areas/AdminSpecial/Controllers/BookController.cs
using Kitap.BLL.RepositoryPattern.ConcreteRepo;
using Kitap.MODEL.Entities;
using Kitap.TOOLS.MyTools;
using MVCUI.AuthenticationClasses;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCUI.Areas.AdminSpecial.Controllers
{
    [AdminAuthentication]
    public class BookController : Controller
    {
        BookRepository b_repo = new BookRepository();
        CategoryRepository cat_repo = new CategoryRepository();
        // GET: AdminSpecial/Book
        public ActionResult BookList()
        {
            return View(b_repo.SelectActives());
        }

        public ActionResult AddBook()
        {
            return View(Tuple.Create(new Book(),cat_repo.SelectActives()));
        }

        [HttpPost]
        public ActionResult AddBook([Bind(Prefix ="Item1")] Book item,HttpPostedFileBase resim)
        {
            item.ImagePath = ImageUploader.UploadImage("~/Pictures/", resim);
            b_repo.Add(item);

            return RedirectToAction("BookList");
        }

        public ActionResult UpdateBook(int id)
        {
            return View(Tuple.Create(b_repo.GetByID(id),cat_repo.SelectActives()));
        }

        [HttpPost]
        public ActionResult UpdateBook([Bind(Prefix = "Item1")] Book item, HttpPostedFileBase resim)
        {
            item.ImagePath = ImageUploader.UploadImage("~/Pictures", resim);
            b_repo.Update(item);

            return RedirectToAction("BookList");
        }

        public ActionResult DeleteBook(int id)
        {
            b_repo.SpecialDelete(id);
            return RedirectToAction("BookList");
        }

        public ActionResult BookDetail(int id)
        {
            return View(b_repo.GetByID(id));
        }
    }
}

MVCUI/Areas/AdminSpecial/Controllers/CategoryController.cs
using Kitap.BLL.RepositoryPattern.ConcreteRepo;
using Kitap.MODEL.Entities;
using MVCUI.AuthenticationClasses;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCUI.Areas.AdminSpecial.Controllers
{
    [AdminAuthentication]
    public class CategoryController : Controller
    {
        CategoryRepository cat_repo = new CategoryRepository();
        // GET: AdminSpecial/Category
        public ActionResult CategoryList()
        {
            return View(cat_repo.SelectActives());
        }

        public ActionResult AddCategory()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddCategory(Category item)
        {
            cat_repo.Add(item);
            return RedirectToAction("CategoryList");
        }

        public ActionResult UpdateCategory(int id)
        {
            return View(cat_repo.GetByID(id));
        }

        [HttpPost]
        public ActionResult UpdateCategory(Category item)
        {
            cat_repo.Update(item);
            return RedirectToAction("CategoryList");
        }

        public ActionResult DeleteCategory(int id)
        {
            cat_repo.SpecialDelete(id);
            return RedirectToAction("CategoryList");
        }
    }
}

MVCUI/Areas/AdminSpecial/Views/Category/AddCategory.cshtml
@model Category
@{
    ViewBag.Title = "AddCategory";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>AddCategory</h2>

<div class="col-md-9">
    @using (Html.BeginForm("AddCategory", "Category", FormMethod.Post))
    {
        <div>
            Kategori İsmi Giriniz
        </div>
        <div>
            @Html.TextBoxFor(x => x.CategoryName, new { @class = "form-control" })
        </div>
        <div>
            Acıklama Giriniz
        </div>
        <div>
            @Html.TextBoxFor(x => x.Description, new { @class = "form-control" })
        </div>
        <div>
            <button class="btn btn-primary"> Ekle </button>
        </div>
    }

</div>

MVCUI/Areas/AdminSpecial/Views/Category/CategoryList.cshtml
@using GridMvc.Html
@model List<Category>
@{
    ViewBag.Title = "CategoryList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>CategoryList</h2>

@section Deneme{
    @Html.ActionLink("Yazarları Listele", "AuthorList", "Author", new { area = "AdminSpecial" }, new { @class = "list-group-item" })

    @Html.ActionLink("Kitapları Listele", "BookList", "Book", new { area = "AdminSpecial" }, new { @class = "list-group-item" })

    @Html.ActionLink("Kullanıcıları Listele", "ListAppUsers", "AppUser", new { area = "AdminSpecial" }, new { @class = "list-group-item" })

    @Html.ActionLink("Çıkış Yap", "LogOut", "AppUser", new { area = "AdminSpecial" }, new { @class = "btn btn-success" })

}

@Html.ActionLink("Kategori Ekle", "AddCategory", null, new { @class = "btn btn-primary" })

<div class="col-md-9">

    <div class="panel panel-body">
        <!-- #region Eski Usul Tablo -->
        @*<table class="table table-hover">
                <thead>
                    <tr>
                        <th> Kategori İsmi</th>
                        <th>Kategori Acıklaması</th>
                        <th> Güncelle</th>
                        <th>Sil  </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (Category item in Model)
                    {
                        <tr>
                            <td>@item.CategoryName</td>
                            <td>@item.Description</td>
                            <td>@Html.ActionLink("Güncelle", "UpdateCategory", new { id = item.ID }, new { @class = "btn btn-warning" })</td>
                            <td>@Html.ActionLink("Sil", "DeleteCategory", new { id = item.ID }, new { @class = "btn btn-danger" })</td>
                        </tr>
                    }
                </tbody>
            </table>*@

        <!-- #endregion -->

        @Html.Grid(Model).Columns(c =>
   {
       c.Add(ct => ct.CategoryName)
       .Titled("Kategori İsmi");

       c.Add(ct => ct.Description)
       .Titled("Kategori Açıklaması");

       c.Add().Encoded(false).Sanitized(false).Titled("Güncelle").RenderValueAs(ct => Html.ActionLink("Güncelle", "UpdateCategory", new { id = ct.ID }, new { @class = "btn btn-warning" }).ToHtmlString());

       c.Add().Encoded(false).Sanitized(false).Titled("Sil").RenderValueAs(ct => Html.ActionLink("Sil", "DeleteCategory", new { id = ct.ID }, new { @class = "btn btn-danger" }).ToHtmlString());

   }).WithPaging(10).Sortable(true)

    </div>

</div>

MVCUI/Areas/AdminSpecial/Views/Category/UpdateCategory.cshtml
@model Category
@{
    ViewBag.Title = "UpdateCategory";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>UpdateCategory</h2>

<div class="col-md-9">
    @using (Html.BeginForm("UpdateCategory", "Category", FormMethod.Post))
    {
        @Html.HiddenFor(x => x.ID)
        <div>
            Kategori İsmi Güncelleyiniz
        </div>
        <div>
            @Html.TextBoxFor(x => x.CategoryName, new { @class = "form-control" })
        </div>
        <div>
            Acıklamayı Güncelleyiniz
        </div>
        <div>
            @Html.TextAreaFor(x => x.Description, new { @class = "form-control" })
        </div>
        <div>
            <button class="btn btn-primary"> Güncelle </button>
        </div>
    }


</div>